DOMAIN = "afd_pump"
DEFAULT_PREFIX = "AFD"
DEFAULT_NAME = "AFD Pump Controller"

# MQTT топики (относительно префикса)
TOPIC_SET = "set"
TOPIC_STATE = "state"
TOPIC_LEVEL = "level"
TOPIC_AVAILABILITY = "availability"
TOPIC_CALIBRATE_STATE = "calibrate/state"
TOPIC_CALIBRATE_ONGOING = "calibrating"
TOPIC_CALIBRATE_VOLUME = "calibrate/volume"
TOPIC_CALIBRATE_VOLUME_SET = "calibrate/volume/set"
TOPIC_CALIBRATE_START = "calibrate/start"
TOPIC_CALIBRATE_STOP = "calibrate/stop"
TOPIC_DISPENSE_VOLUME = "dispense/volume"
TOPIC_DISPENSE_VOLUME_SET = "dispense/volume/set"
TOPIC_DISPENSE_RUN = "dispense/run"
TOPIC_DISPENSE_STOP = "dispense/stop"
TOPIC_DISPENSE_FINISHED = "dispense/finished"
TOPIC_BRIGHTNESS = "brightness"
TOPIC_BRIGHTNESS_SET = "brightness/set"
TOPIC_SCHEDULE = "schedule"
TOPIC_SCHEDULE_ADD = "schedule/add"
TOPIC_SCHEDULE_REMOVE = "schedule/remove"
TOPIC_SCHEDULE_UPDATE = "schedule/update"
TOPIC_SCHEDULE_GET = "schedule/get"
TOPIC_SCHEDULE_RESULT = "schedule/result"

# Атрибуты для сенсоров
ATTR_FLOW_RATE = "flow_rate"
ATTR_CALIBRATING = "calibrating"
ATTR_CALIBRATED = "calibrated"
ATTR_TARGET_VOLUME = "target_volume"
ATTR_ELAPSED_SEC = "elapsed_sec"
ATTR_REMAINING_SEC = "remaining_sec"
ATTR_FIXED = "fixed"

# Сервисы
SERVICE_CALIBRATE_START = "calibrate_start"
SERVICE_CALIBRATE_STOP = "calibrate_stop"
SERVICE_CALIBRATE_SET_VOLUME = "calibrate_set_volume"
SERVICE_DISPENSE_RUN = "dispense_run"
SERVICE_DISPENSE_STOP = "dispense_stop"
SERVICE_DISPENSE_SET_VOLUME = "dispense_set_volume"
SERVICE_SET_BRIGHTNESS = "set_brightness"
SERVICE_SCHEDULE_ADD = "schedule_add"
SERVICE_SCHEDULE_REMOVE = "schedule_remove"
SERVICE_SCHEDULE_UPDATE = "schedule_update"
SERVICE_SCHEDULE_GET = "schedule_get"